empresa_seguimento:
    resource: "@EmpresaBundle/Resources/config/routing/seguimento.yml"
    prefix:   /seguimento

backend_empresa:
    resource: "@EmpresaBundle/Resources/config/routing/empresa.yml"
    prefix:   /
    
backend_seguimento:
    resource: "@EmpresaBundle/Resources/config/routing/seguimento.yml"
    prefix:   /seguimento
