dashboard:
    resource: "@DashboardBundle/Resources/config/routing.yml"
    prefix:   /
    
backend_seguimento:
    resource: "@BackendBundle/Resources/config/routing/seguimento.yml"
    prefix:   /seguimento

