empresa:
    path:     /
    defaults: { _controller: "BackendBundle:Empresa:index" }

empresa_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:Empresa:show" }

empresa_new:
    path:     /new
    defaults: { _controller: "BackendBundle:Empresa:new" }

empresa_create:
    path:     /create
    defaults: { _controller: "BackendBundle:Empresa:create" }
    methods:  POST

empresa_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:Empresa:edit" }

empresa_update:
    path:     /{id}/update
    defaults: { _controller: "BackendBundle:Empresa:update" }
    methods:  [POST, PUT]

empresa_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:Empresa:delete" }
    methods:  [POST, DELETE]
