empresa:
    path:     /
    defaults: { _controller: "BackendBundle:Empresa:index" }

empresa_new:
    path:     /novo
    defaults: { _controller: "BackendBundle:Empresa:new" }

empresa_create:
    path:     /criar
    defaults: { _controller: "BackendBundle:Empresa:create" }
    methods:  POST

empresa_edit:
    path:     /{id}/editar
    defaults: { _controller: "BackendBundle:Empresa:edit" }

empresa_update:
    path:     /{id}/atualizar
    defaults: { _controller: "BackendBundle:Empresa:update" }
    methods:  [POST, PUT]
