seguimento:
    path:     /
    defaults: { _controller: "BackendBundle:Seguimento:index" }

seguimento_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:Seguimento:show" }

seguimento_new:
    path:     /new
    defaults: { _controller: "BackendBundle:Seguimento:new" }

seguimento_create:
    path:     /create
    defaults: { _controller: "BackendBundle:Seguimento:create" }
    methods:  POST

seguimento_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:Seguimento:edit" }

seguimento_update:
    path:     /{id}/update
    defaults: { _controller: "BackendBundle:Seguimento:update" }
    methods:  [POST, PUT]

seguimento_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:Seguimento:delete" }
    methods:  [POST, DELETE]
